### ISSUE TITLE
[Feature Request] TOC+BIN-based CHD support

### ISSUE THREAD

**Issue by vpelletier** [MiSTer-devel/PSX_MiSTer#183]
CHD files can contain CUE+BIN but also TOC+BIN (as produced by cdrdao). The main difference is that TOC+BIN can contain subchannels, which avoid the need for `.sbi` files for libcrypt-protected games, whereas CUE+BIN do not support subchannels at all.

As of the release dated 22.08.13, such CHD loads fine but the subchannels seem ignored (re-constructed by the core, if I am reading the code correctly), leading to broken libcrypt and requiring `.sbi` files.

I am not sure what the best approach is.

One which may be relatively easy and not require an interface change could be to act as-if an `.sbi` file was present when the subchannels are present and usable (I guess this requires raw subchannels), generating its content from the subchannels (assuming there is an easy way of generating these) and presenting the result to the core.

**Comment by birdybro** [comment]
I believe most if not all of this would be handled in Main_MiSTer not in the core?

**Comment by vpelletier** [comment]
If this goes in the direction I suggest, then indeed it would happen in Main_MiSTer. But I think some consensus on the core side would be welcome before moving there: maybe there are already different plans, better ideas...

**Comment by RobertPeip** [comment]
the sbi handling in the core is super simple and small and working. I don't see any reason to exchange this inside the core to anything else.

How this is handled in main is another topic. Maybe someone would want to do it, but it seems much work for only very few users. A full set of .sbi for all games is smaller a single subchannel for one game and works 100% without any extra effort.

**Comment by vpelletier** [comment]
Good points. 96 extra bytes per sector is 4% more storage space needed (ignoring possible compression inconsistencies), or 10MB to 30MB per 700MB CD.

An argument in favor of in-image subchannels is that I only have to have the original CD to get those. I do not need to figure out where to get SBI files from, how to store them, and whether a given CD has libcrypt to begin with (information which I found rather hard to locate, and it seems not all games cleanly break when they have it).

Anyway, I have no problem with the core remaining unaffected, so I close this issue. I may toy with main to see if adding support there is possible in a simple-enough patch.

**Comment by birdybro** [comment]
For anyone else reading along and curious, there are 230 SBI files in total, and all of them are for European versions of games because there was special copy protection added there.

![image](https://user-images.githubusercontent.com/16388068/185824537-d5d38bec-8899-4641-8852-3913d1111bd2.png)

The SBI files aren't 10-30MBytes per 700MByte CD, they are exactly 452 bytes per game. How much space that actually occupies depends on your filesystem.

http://redump.org/sbi/psx/ - SBI files in case anyone needs them if they find this topic. If you use a Redump set then they are already named correctly and you only need to drop them in the folder of the game you want to play which needs it.
