### ISSUE TITLE
Crash Bash with NTSC/Pal Region Selector won't boot at all

### ISSUE THREAD

**Issue by cuentademierda1234567890** [MiSTer-devel/PSX_MiSTer#184]
Issue: Game won't boot at all

How to reproduce the bug: Just boot up an image of Crash Bash with ntsc/pal region selector

WorkAround: there isn't but keep in mind fixing this will make the core more accurate to the real Hardware like it should be think it more like a benchmark of accuracy for the core

Bios Used:

- 	SCPH-7001
-	SCPH-7000
-	SCPH-7002

CD Image: SCES_028.34 but the image is an special image with NTSC/PAL selector
the selector looks like this
[https://www.youtube.com/watch?v=2QhhAQZ-iWo](url)

Core Version: PSX v220727

Also I provide an Image of the region selector so to aware you which bin\cue I'm talking about

![cras bash](https://user-images.githubusercontent.com/62609619/185764970-b548cb09-7fba-41d8-aaf1-0bb909572387.png)

**Comment by Fuzzybane** [comment]
remove the link please, any romhacks that cause bugs are not considered a core bug, most people will just use either the NTSC or the PAL version of the game as they see fit

**Comment by cuentademierda1234567890** [comment]
But even if it's a "romhack" it can be useful for testing accuracy of the core don't you think ? I mean in the real hardware it works like a charm so should be working in the psx core :-)

**Comment by Fuzzybane** [comment]
I do agree with that but if you are gonna post a link can you change it to the patch you are using rather than a link to the game, we don't want pirated links on the github or in the discord :)

**Comment by cuentademierda1234567890** [comment]
ok I'll delete the link to the rom instead I'm gonna look for some image or video of the specific rom i'm talking about thanks !!!

**Comment by Fuzzybane** [comment]
no worries can you also do the same to the crash trilogy post you made :) thank you

**Comment by cuentademierda1234567890** [comment]
> no worries can you also do the same to the crash trilogy post you made :) thank you

Thank you very much for you understanding I just happen to love Crash Bandicoot and Spyro and also Ps1 cause I grew up with it I only wanted to leave my grain of sand so developers can notice details like this and make a super accurate core :-) have a great day!!! hopefully this will be resolved soon :-) hehehe

**Comment by Fuzzybane** [comment]
yeah sorry if I came across as harsh we just don't condone piracy and link sharing and I have been actively testing the core since the start so I totally understand the need and want for accuracy and we have never taken patched/romhacked/cheats (when they were added) as bugs considering they change the way games handle certain things :-) hope you also have a great day

**Comment by RobertPeip** [comment]
The workaround is to use the built in pal/ntsc select of the core with the normal game.

Sure, at some point, the core should support all kind of weird homebrew, but i will not spend my time debugging something that has zero value.

I will close this here due to posting a link. Even if removed, it's still in the history.
