### ISSUE TITLE
Games with Odd Timing Issues

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#80]
Gex 2 and 3

Castlevania - Symphony of the Night

Soul Reaver

**Workaround**
[psx]
vsync_adjust=0
In MiSTer.ini

**Comment by AtomicShroom** [comment]
How does this manifest itself in Gex 2/3?

Because I’m playing Gex 2 lately and sometimes when I boot the game, no image is shown, and I can only hear the sound of the intro FMVs. When it happens controls are unresponsive and I have no choice but to reset the game until the image decides it wants to show up. Takes 2-5 tries sometimes.  Is this what this issue is about?

**Comment by Fuzzybane** [comment]
> How does this manifest itself in Gex 2/3?
> 
> Because I’m playing Gex 2 lately and sometimes when I boot the game, no image is shown, and I can only hear the sound of the intro FMVs. When it happens controls are unresponsive and I have no choice but to reset the game until the image decides it wants to show up. Takes 2-5 tries sometimes. Is this what this issue is about?

that is what the initial report was yeah, when I was told about this I loaded Gex 2 then switched to Gex 3 like 6 times each and game started everytime, it was only then that I found out that the only difference was I was on vsync 0 and they were on 2 I believe, they then changed to 0 and worked everytime for them as well, they switched back to 2 and got the same result they had before

**Comment by Fuzzybane** [comment]
closing as this issue is fixed
